### ISSUE TITLE
Error: BrowserModule has already been loaded.

### ISSUE THREAD

**Issue by manavgoel** [passenger6/ngx-aside#1]
I get this error when I tried to use the library in my angular-4 project. Upon surfing the net I came upon the source of problem, which is we can't include `BrowserAnimationsModule` twice in our app. (pretty similar to `BrowserModule`, it's always recommended to include `CommonModule` instead so as to create platform/browser independent modules) 
Please refer this [issue](https://github.com/angular/angular-cli/issues/5684)

So I guess it's due to the `BrowserAnimationsModule` that you have imported in your `aside.module.ts` file. As it happens to be I've already imported `BrowserAnimationsModule` in my `app.module`, so when I try to use this library it conflicts with the second import.

I guess a simple solution to this is you might not include `BrowserAnimationsModule` in feature modules like `aside.module` as it'll always be able to use the dependencies injected at the root level. Instead you might add this to your `readme` file to include `BrowserAnimationsModule` at the root level in order to use animations flawlessly with `ngx-aside`.

Could you please look into this, and update the repo with appropriate solution. Thanks.

**Comment by passenger6** [comment]
@manavgoel

Could you provide an example? I can’t reproduce this problem. For testing I imported ‘BrowserAnimationsModule’ and 'NgReduxModule' together in app.module.ts and then I used <ngx-aside></ngx-aside> in my app.component all has been working fine.  

Do you use lazy loading? 

I use:
```
"@angular/core "^4.3.6",
"@angular/animations": "^4.3.6"
```

**Comment by manavgoel** [comment]
@passenger6 

Apologies for a late reply, got caught up somewhere else.

As a matter of fact, Yes I'm using lazy loading (forgot to mention). That's the reason why it hit's me with this error. When I try using `ngx-aside` in eagerly loaded components it works beautifully. 

I read about the lazy loaded components being injected by a separate `child injector` in the DI tree. I guess when my lazy loaded component (which uses `ngx-aside`) is induced in the app, it conflicts with the already included `BrowserAnimationsModule ` at the root level. 

Even I'm using the latest versions, but I don't think that the error lies there. Thanks.

**Comment by manavgoel** [comment]
@passenger6

Hi, any updates on this ?

**Comment by passenger6** [comment]
Hi, thank you for your feedback. It took unfortunately a little bit long, but i fixed this problem. :)

**Comment by manavgoel** [comment]
cool 👍
