### ISSUE TITLE
Error: error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'. ng ver 6.1.4

### ISSUE THREAD

**Issue by e2video** [passenger6/ngx-aside#4]
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-aside/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

WARNING in ./node_modules/ngx-aside/node_modules/@angular/core/esm5/core.js
6570:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/ngx-aside/node_modules/@angular/core/esm5/core.js
6590:15-102 Critical dependency: the request of a dependency is an expression

**Comment by sarfarazansari** [comment]
@e2video , @passenger6  check out [angular 6](https://github.com/sarfarazansari/ngx-aside)

**Comment by passenger6** [comment]
ngx-aside 1.4.0 is now angular 6 compatible
