### ISSUE TITLE
update library for angular 6

### ISSUE THREAD

**Issue by sarfarazansari** [passenger6/ngx-aside#5]
[feature request] @passenger6 
I've updated library to angular 6 version and tested. it's working fine.
could you please look into that and publish it so we can use in our project.
here is a link [ngx-aside](https://github.com/sarfarazansari/ngx-aside)

**Comment by passenger6** [comment]
@sarfarazansari

Thank you for your changes! Can you please create pull request?

**Comment by sarfarazansari** [comment]
@passenger6 am unable to create a `PR`.

reason I've pushed my code using `-f`.

FYI I've initiated the snippet from scratch by using `angular-cli`.
because using `ng update` causing issues and not able to fix them all manually.

So we have two options now.
Either we rewrite the whole repo or you can add one more repo for angular version greater than 6.

**Comment by sarfarazansari** [comment]
@passenger6 any update?

**Comment by sarfarazansari** [comment]
@passenger6  am going to create a PR for this

**Comment by sarfarazansari** [comment]
@passenger6  [here is the PR for angular 6](https://github.com/passenger6/ngx-aside/pull/6)

let me know if you have any issue

**Comment by passenger6** [comment]
thank you for your work 👍  (merged)
